# Generated by Django 3.0.2 on 2020-07-25 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movielist',
            old_name='genres',
            new_name='genre',
        ),
    ]
